# Generated by Django 6.0.3 on 2026-05-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(default=200)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('cloud_name', models.CharField(default='LOCAL', max_length=50)),
                ('is_booking', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
